---
# tasks file for myweb
- name: "install docker"
  yum:
    name: docker
    state: installed
  notify: 
    - restartservice
- name: "install nmap"
  yum:
    name: nmap
    state: installed

- name: "install nginx"
  yum:
    name: nginx
    state: installed
  notify: 
    - restartservice

